apiVersion: v1
kind: ConfigMap
metadata: 
  name: fiber-feed-config-map-grafana-dashboard
data: 
  NEWS_SERVICE_PORT: "3000"
  SEARCH_SERVICE_PORT: "3001"
  DB_PORT: "5432"
  DB_NAME: "newsDB"
  DB_HOST: "localhost"
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['<node-ip>:9100']
  k8s-dashboard.json: |
    {
      "title": "Kubernetes Cluster",
      "panels": [...]
    }
  