apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: DB_USER
          valueFrom: 
            configMapKeyRef:
              name: postgresConfig
              key: DB_USER
          value: "user"
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: posg
          key : "DB_PASSWORD"
        - name: DB_NAME
          value: "newsdb"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
